### ISSUE TITLE
Duels don't start Error Log Spam

### ISSUE THREAD

**Issue by Maitlans** [Enzias/EasyDuels#2]
It just says spamming "Starting in 3" and that's it.

[23:26:23 WARN]: [EasyDuels] Task #7402 for EasyDuels v1.1.0 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_NOTE_HARP
        at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
        at org.bukkit.Sound.valueOf(Sound.java:11) ~[patched_1.16.1.jar:git-Paper-101]
        at fr.enzias.easyduels.managers.versions.SenderManager_1_16_R1.sendSound(SenderManager_1_16_R1.java:59) ~[?:?]
        at fr.enzias.easyduels.managers.TimerManager.run(TimerManager.java:50) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-101]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Enzias** [comment]
Hello!
From what I see, you are running version 1.16.1 on your server. However, I think that you use the basic configuration of the plugin on your server. But as mentioned in the wiki (https://github.com/Enzias/EasyDuels/wiki/Basic-Configuration), the basic configuration will only work in 1.12 because I put 1.12 sounds.
You will need to modify(or to check) the values of the new sounds (i.g 1.16+). Here is a link where you can find all of them: [1.16 sounds](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)
As an example, in 1.16, the sound BLOCK_NOTE_HARP (1.12) is replaced by BLOCK_NOTE_BLOCK_HARP.
Most of the changes are minor between the 1.12 and 1.16 sounds. But in 1.16, you have access to new sounds.

Hoping that the problem is solved. Have a good day and do not hesitate to share a review on [here](https://www.spigotmc.org/resources/%E2%9A%94%EF%B8%8Feasyduels%E2%9A%94%EF%B8%8F-a-complete-1v1-system-1-12-x-1-16-x.83031/) to help me ^^

Edit: I will see to add different basic configurations for every version supported by EasyDuels.

**Comment by Maitlans** [comment]
Thank you! That was it, closing issue 👍
