### ISSUE TITLE
Timer Fails on 3 seconds left. Round doesn't "start"

### ISSUE THREAD

**Issue by Nefarious01** [Enzias/EasyDuels#5]
PaperMC 1.16.2

The issue I have encountered is when the players get teleported to the arena spawns, the counter stops at 3. If a player quits the game, the match ends and everything works as normal. Awards works, fireworks, etc. 

[12:22:34] [Server thread/WARN]: [EasyDuels] Task #732251 for EasyDuels v1.4.1 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_NOTE_HARP
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.Sound.valueOf(Sound.java:11) ~[patched_1.16.2.jar:git-Paper-189]
	at fr.enzias.easyduels.managers.versions.SenderManager_1_16_R2.sendSound(SenderManager_1_16_R2.java:74) ~[?:?]
	at fr.enzias.easyduels.managers.CountdownManager.sendLobbyTimer(CountdownManager.java:40) ~[?:?]
	at fr.enzias.easyduels.tasks.TimerManager.run(TimerManager.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-189]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by Enzias** [comment]
Hey! Take a look at here: https://github.com/Enzias/EasyDuels/issues/2 ^^

**Comment by Nefarious01** [comment]
Oh, my apologies! I didn't even notice that, Thanks!

**Comment by Enzias** [comment]
No problem @Nefarious01 ! If you have any other issues or suggestions do not hesitate to open an issue here! Also do not hesitate to leave a review! Have a good night!
