### ISSUE TITLE
please support 1.16.4

### ISSUE THREAD

**Issue by CuteLittleSky** [Enzias/EasyDuels#7]
please support 1.16.4

**Comment by Enzias** [comment]
Hey what is the problem with this version ? It should work well 🤔👍

**Comment by CuteLittleSky** [comment]
> Hey what is the problem with this version ? It should work well

Unexpected exception while parsing console command "EasyDuels"
org.bukkit.command.CommandException: Cannot execute command 'easyduels' in plugin EasyDuels v1.5.0 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:764) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:412) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1270) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[17:37:18] [Server thread/INFO]: [EasyDuels] Enabling EasyDuels v1.5.0
[17:37:18] [Server thread/WARN]: [EasyDuels] [EasyDuels] Failed to load EasyDuels! Unsupported version.
[17:37:18] [Server thread/INFO]: [EasyDuels] Disabling EasyDuels v1.5.0
[17:37:18] [Server thread/INFO]: [EasyDuels] Plugin successfully disabled.

**Comment by Enzias** [comment]
Ohh okay sorry about it, I'll fix it in the next update, sorry for the inconvenience ^^'

**Comment by Enzias** [comment]
A version for 1.16.4 version is available on the discord server ^^
